version: '3.8'
services:
  db:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - '9432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # Create triggers
      - ./sql/init-functions-triggers.sql:/docker-entrypoint-initdb.d/10-init-functions-triggers.sql
      # Create tables
      - ./sql/init_tables.sql:/docker-entrypoint-initdb.d/20-init_tables.sql
      # Shared folder 
      - app-data:/tmp:z

  service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    links:
      - db
    networks: 
      - default
    ports:
      - 8888:8888
    volumes:
      - app-data:/tmp:z
volumes:
  postgres-data:
  app-data: